const nome = prompt('Digite seu nome completo: ')
document.body.innerHTML += `Seu nome é <strong>${nome}</strong>, seja bem vindo ao meu Site. </br>`
document.body.innerHTML += `Seu nome tem <strong>${nome.length}</strong> caracteres. </br>`
document.body.innerHTML += `a segunda letra do seu nome é <strong>${nome.toUpperCase()[1]}</strong> </br>`
document.body.innerHTML += `O índice da letra <strong>${nome.toUpperCase()[1]}</strong> é o <strong>'1'</strong> </br>`
document.body.innerHTML += `A ultima letra do seu nome é <strong>${nome.slice(-1)}</strong> </br>`
document.body.innerHTML += `As 3 ultimas letra do seu nome é <strong>${nome.slice(-3)}</strong></br>`
document.body.innerHTML += `As palavras do seu nome são: <strong>${nome.split(' ', 3)}</strong></br>`
document.body.innerHTML += `Seu nome com letras minusculas é - <strong>${nome.toLowerCase()}</strong></br>`
document.body.innerHTML += `Seu nome com letras Maiusculas é - <strong>${nome.toUpperCase()}</strong>`
